name: outwriter

on:  [push,pull_request]
   
jobs:  
   write:
      runs-on: windows-latest
      steps:
        - name: typecheck
          uses: actions/checkout@v2
        - name: Changed Files Exporter
          uses: umani/changed-files@v4.0.0
          with:
            repo-token: ${{ github.token }}
            pattern: '^.*\.(md|markdown)$'
